# Generated by Django 4.2.4 on 2023-08-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marsa", "0002_port_quai_postenavire_navire_affectation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quai",
            name="type",
        ),
    ]
