# Generated by Django 4.2.4 on 2023-08-21 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marsa", "0008_remove_navire_port_remove_navire_postenavire_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("capacite", models.PositiveIntegerField()),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marsa.port"
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosteNavire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("taille_max", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_arrivee", models.DateField()),
                ("heure_arrivee", models.TimeField()),
                ("date_depart", models.DateField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("charge", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "quai_assigne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marsa.quai"
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Navire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroDeScanne", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_marchandise",
                    models.CharField(
                        choices=[
                            ("conteneurs", "Conteneurs"),
                            ("vrac_sec", "Vrac sec"),
                            ("vrac_liquide", "Vrac liquide"),
                            ("marchandises_generales", "Marchandises générales"),
                            ("marchandises_dangereuses", "Marchandises dangereuses"),
                            ("produits_chimiques", "Produits chimiques"),
                            ("hydrocarbures", "Hydrocarbures"),
                            ("minerais", "Minerais"),
                            ("denrees_alimentaires", "Denrées alimentaires"),
                            ("bois", "Bois"),
                            ("machines_et_equipements", "Machines et équipements"),
                            ("textiles", "Textiles"),
                            ("equipements_medicaux", "Équipements médicaux"),
                            ("vehicules", "Véhicules"),
                            ("produits_electroniques", "Produits électroniques"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacite", models.PositiveIntegerField()),
                ("date_arrivee", models.DateField()),
                ("heure_arrivee", models.TimeField()),
                ("date_depart", models.DateField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("shifts_requis", models.PositiveIntegerField(default=0)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marsa.port"
                    ),
                ),
                (
                    "posteNavire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marsa.postenavire",
                    ),
                ),
                (
                    "quai_de_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marsa.quai"
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "navire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="marsa.navire"
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="marsa.port"
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marsa.postenavire",
                    ),
                ),
                (
                    "quai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="marsa.quai"
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
